### ISSUE TITLE
GitHub button doesn't redirect to the repository

### ISSUE THREAD

**Issue by sudojunior** [SnakeyStyles/Snakey#2]
1. Navigate to extension page
2. Click GitHub button

Expected: Redirection to https://github.com/SnakeyStyles/Snakey
Actual: No further action.

**Comment by sudojunior** [comment]
Ref to the below since it prevents the page from moving away from its previous / existing state. https://github.com/SnakeyStyles/Snakey/blob/19041100d5436555d495d8f21d676d185470ceb0/js/background/listeners.js#L74

**Comment by Snazzah** [comment]
Not sure what you mean by preventing from moving from its state, that's to prevent parsing when you view the file in github and not github user content. It should probably be `blob` but I'll look into it.

Was in a bit of a rush, but I fixed it in 0f3908d.
